name: Auto Updater

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '25 4,16 * * 1-5' # every day at 4:34 and 16:34
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      # 默认为开发环境
      ENVIRONMENT: development
    steps:
    - uses: actions/checkout@v4

    - name: Set environment variables
      id: env
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
        fi

    - name: Reset local changes
      run: |
        git fetch origin main
        git reset --hard origin/main

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run fetchEarningsCalendarData script
      run: node ./api/github_get.js
      env:
        SHOULD_GEN_SELECTED: ${{ vars.SHOULD_GEN_SELECTED }}
        SHOULD_GEN_ALL: ${{ vars.SHOULD_GEN_ALL }}

    - name: Waiting for 10 seconds
      run: sleep 3

    - name: Run genAllIcs script
      run: node ./api/github_gen.js
      env:
        SHOULD_GEN_SELECTED: ${{ vars.SHOULD_GEN_SELECTED }}
        SHOULD_GEN_ALL: ${{ vars.SHOULD_GEN_ALL }}

    - name: Upload multiple files
      uses: actions/upload-artifact@v4
      with:
        name: OhEarningsCal-results
        path: |
          datas/**/*.json
          storedData/**/*.json


    - name: Commit files
      env:
        # 在源仓库的 Settings -> Secrets -> Actions 中设置 DEPLOY_KEY
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      run: |
        if [ "$ENVIRONMENT" = "production" ]; then

            echo "Running production deployment"
            
            # 设置 SSH
            mkdir -p ~/.ssh
            echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            # 配置 Git
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            
            # 克隆目标仓库
            git clone git@github.com:cbmland/CloudStatic.git target_repo
            
            
            # 复制构建产物到目标仓库
            cp -r docs/* target_repo/
            
            # 提交并推送
            cd target_repo
            touch dummy.txt
            git add .
            CURRENT_DATE=$(date +"%Y-%m-%d")
            git commit -m "chore: trigger workflow - $CURRENT_DATE" -a || echo "No changes to commit"
            git push origin main

        else

          echo "Running development deployment"
          
        fi